CREATE TABLE IF NOT EXISTS posts (
    Id SERIAL PRIMARY KEY, 
    Body TEXT NOT NULL,
    FirstCreated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    LastUpdated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)
